trigger:
  batch: true
  branches:
    include:
      - master

pr:
  - master

stages:
  - stage: Test
    jobs:
      - job: Test
        pool:
          vmImage: 'ubuntu-latest'

        steps:

          - checkout: self
            fetchDepth: 1
            clean: true

          - bash: |
              npm install
              npm test
            displayName: Test
          - task: DockerInstaller@0
            displayName: Docker Installer
            inputs:
              dockerVersion: 18.09.9
              releaseType: stable

          - bash: |
              set -ex
              export REPORT_PATH=$(pwd)/report
              docker run -t --rm -v \
                $REPORT_PATH: \
                -e PASSWORD=e98d24a9-286e-4dce-8b01-2a507125986b  \
                -e PROJECT_ID=332250 \
                -e TYPE=katalon \
                -e REPORT_PATH= \
                katalonstudio/report-uploader:0.0.8
            displayName: Upload report to Katalon TestOps
            env:
              KATALON_API_KEY: e98d24a9-286e-4dce-8b01-2a507125986b